# Generated by Django 4.2.3 on 2023-07-05 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Pending'), ('2', 'Started'), ('3', 'Done')], default='1'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todo.taskitem'),
        ),
    ]
